source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "7.0"

link_with 'flips-QA', 'flips-DEV', 'flips-PROD'

pod 'AFNetworking', '2.4.1'
pod 'Masonry', '0.5.3'
pod 'Facebook-iOS-SDK', '3.19.0'
pod 'PubNub', '3.7.9.3'
pod 'MagicalRecord/Shorthand', '~> 2.2'
pod 'SplunkMint-iOS', '4.0.21'
pod 'FlurrySDK'
