source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "7.0"

link_with 'flips', 'flipsTests'

pod 'AFNetworking', '2.4.1'
pod 'Masonry', '0.5.3'
pod 'Facebook-iOS-SDK', '3.19.0'
pod 'PubNub', '3.7'
pod 'MagicalRecord/Shorthand', '~> 2.2'
pod 'RHAddressBook', '1.1.1'
pod 'SplunkMint-iOS', '4.0.21'
pod 'FlurrySDK'
