source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "7.0"

link_with 'mugchat', 'mugchatTests'

pod 'AFNetworking', '2.4.1'
pod 'Masonry', '0.5.3'
pod 'Facebook-iOS-SDK', '3.19.0'
pod 'PubNub', '3.6.7'
pod 'MagicalRecord/Shorthand', '~> 2.2'
pod 'MBContactPicker'
